name: Build and Test

on: push

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v6
              with:
                python-version: '3.x'
            
        
            - name: install dependencies [pip]
              run: |
               python -m pip install pip --upgrade pip
               pip install pytest
               pip install pytest-mock
               if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            

            - name: run unit tests [pytest]
              run: pytest



