name: Build and Test

on: push

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python@v6
        
            - name: install dependencies [pip]
              run: |
               python -m pip install pip --upgrade pip
               pip install flake8
               pip install pytest
               if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: run linter [flake8]
              run: flake8 .

            - name: run unit tests [pytest]
              run: pytest



